import Header from "@/components/layouts/header";
import "./globals.css";
import { Providers } from "@/components/Providers";
import Footer from "@/components/layouts/footer";
import { ToastContainer } from "react-toastify";
import CartDialog from "@/components/features/cart/components/CartDialog";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <ToastContainer />
          <CartDialog />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
